### ISSUE TITLE
[Cinnamon Settings] Can't open after Upgrading to 3.6 via Repo Switch

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#7026]
```
~ $ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 43, in <module>
    modules = map(__import__, mod_files)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 7, in <module>
    from ExtensionCore import ExtensionSidePage
ImportError: cannot import name ExtensionSidePage
```

Cinnamon Version: 3.6
Upgrading From: Mint 18.1 (PPA Switch from Sonya to Sylvia)

**Comment by JosephMcc** [comment]
It's not a Cinnamon issue that you didn't do a proper upgrade. The line with the error no longer even exists in Cinnamon3.6.

**Comment by feren** [comment]
@JosephMcc What is the proper way to upgrade when the release isn't out yet?

**Comment by leigh123linux** [comment]
@feren Wait till it's released/ready!
