### ISSUE TITLE
Cinnamon-Menu not starting after update to 6.6.0

### ISSUE THREAD

**Issue by SuicideShow** [linuxmint/cinnamon#13268]
### Distribution

EndeavourOS

### Package version

6.6.0-2

### Graphics hardware in use

Intel Ultra 7 iGPU

### Frequency

Always

### Bug description

I just upgraded my PC and one of the updates was Cinnamon.
Those Packages:
```
cinnamon
cinnamon-control-center
cinnamon-desktop
cinnamon-menus
cinnamon-screensaver
cinnamon-session
cinnamon-settings-daemon
cinnamon-translations
```
After the update i did a reboot and my Start-Menu was gone, also got this error notification:
<img width="468" height="320" alt="Image" src="https://github.com/user-attachments/assets/eab20cf4-360f-4226-b4b3-857757764269" />
So i checked journal and cinnamon-looking-glass, didnt see anything in journal though.
This error was in cinnamon-looking-glass:
```
error t=2025-12-15T17:16:36Z 
[menu@cinnamon.org]: icon.get_names is not a function
[menu@cinnamon.org]: Failed to evaluate 'main' function on applet: menu@cinnamon.org/0
error t=2025-12-15T17:16:36Z 
[menu@cinnamon.org]: Applet menu@cinnamon.org: Could not create applet object.
[menu@cinnamon.org]: Error importing applet.js from menu@cinnamon.org
```

Those are the versions previously installed and the ones it upgraded to:
```
cinnamon-6.4.13-1-x86_64.pkg.tar.zst
cinnamon-6.6.0-2-x86_64.pkg.tar.zst

cinnamon-control-center-6.4.2-1-x86_64.pkg.tar.zst
cinnamon-control-center-6.6.0-1-x86_64.pkg.tar.zst

cinnamon-desktop-6.4.2-1-x86_64.pkg.tar.zst
cinnamon-desktop-6.6.0-1-x86_64.pkg.tar.zst

cinnamon-menus-6.4.0-1-x86_64.pkg.tar.zst
cinnamon-menus-6.6.0-1-x86_64.pkg.tar.zst

cinnamon-screensaver-6.4.1-1-x86_64.pkg.tar.zst
cinnamon-screensaver-6.6.0-1-x86_64.pkg.tar.zst

cinnamon-session-6.4.2-1-x86_64.pkg.tar.zst
cinnamon-session-6.6.1-1-x86_64.pkg.tar.zst

cinnamon-settings-daemon-6.4.3-1-x86_64.pkg.tar.zst
cinnamon-settings-daemon-6.6.1-1-x86_64.pkg.tar.zst

cinnamon-translations-6.4.2-1-any.pkg.tar.zst
cinnamon-translations-6.6.0-1-any.pkg.tar.zst
```

I downgraded to the last working version and the error is gone again, my Menu is back as usual aswell.

### Steps to reproduce

Update from Cinnamon 6.4.x to 6.6.x and reboot PC.

### Expected behavior

Having the Start-Menu like usual.
