### ISSUE TITLE
menu@cinnamon.org: Lock button on menu broken after Cinnamon 6.7.0

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/Cinnamon#13707]
### Distribution

Linux Mint (Alfa on Resolute base)

### Package version

6.7.0

### Frequency

Always

### Bug description

Lock button is not working on menu after Cinnamon 6.7.0. 

```
(cinnamon:108704): St-WARNING **: 00:39:19.159: parse_shadow_property: default case

(cinnamon:108704): Gjs-CRITICAL **: 00:40:53.322: JS ERROR: TypeError: Main.lockscreen is not a function
_refreshSystemButtons/button.activate@/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js:2504:18
_onButtonReleaseEvent@/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js:217:18
```

```
apt policy cinnamon
cinnamon:
  Installed: 6.7.0+alfa
  Candidate: 6.7.0+alfa
  Version table:
 *** 6.7.0+alfa 500
        500 http://packages.linuxmint.com alfa/backport amd64 Packages
        100 /var/lib/dpkg/status
     6.4.13-2 500
        500 http://archive.ubuntu.com/ubuntu resolute/universe amd64 Packages
```

### Steps to reproduce

Upgrade to Cinnamon 6.7.0 and click lock button on menu.

### Expected behavior

Lock screen running when you click the lock button.

### Additional information

I manually upgrade to Alfa (on Resolute base).
