### ISSUE TITLE
skip_taskbar hint stopped working in window-list applet ~4.0

### ISSUE THREAD

**Issue by Lamieur** [linuxmint/cinnamon#8600]
I believe either this commit broke skip_taskbar hint, or some change in... muffin? (I don't know the infrastructure really):
https://github.com/linuxmint/cinnamon/commit/a884e722b9c8e6b846ad972c76c8e84a2ad501fc

Either way, windows with skip_taskbar hint are still shown on the window list (aka taskbar).

I noticed with gkrellm, but you can reproduce with any application, for example:
xclock &
- test that it's visible on the window list and can be switched to with alt-tab
wmctrl -r xclock -b toggle,skip_taskbar
- test that you now can't alt-tab to it, but it's still visible on the window list
- you can toggle it a few times and confirm alt-tab reacts correctly, but window list never updates

What points in the direction of that commit is my ~/.xsession-errors being full of:

(cinnamon:1442): Cjs-WARNING **: 20:39:04.796: JS ERROR: TypeError: window.is_skip_taskbar is not a function
_onWindowSkipTaskbarChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1116:23

**Comment by Lamieur** [comment]
FAO @mtwebster (original commit's author, perhaps something change elsewhere in the meantime and broke it)

**Comment by Lamieur** [comment]
Actually, instead of:
        if (window && window.is_skip_taskbar()) {
it's enough to change line 1116 to:
        if (window && metaWindow.is_skip_taskbar()) {
and the functionality is restored. No idea whether that breaks anything else, but consider this a proposed patch ;)

**Comment by Lamieur** [comment]
Funnily, I also found issue #1178 (https://github.com/linuxmint/cinnamon/issues/1178) but it used to work for years and got broken again only ~6 months ago (when Cinnamon 4.0 landed in Fedora) :)
