### ISSUE TITLE
4.2.0 :: Grouped Window List Applet :: Buggy And Spams Error Log

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/cinnamon#8687]
```
 * Cinnamon 4.2.0
 * Distribution - Arch
 * Graphics - NVIDIA, Driver: NVIDIA
 * 64 bit
 ```

**Issue**
The window list applet is buggy in 4.2. Icons remain in panel after closing apps. Sometimes windows that are still open can't be accessed from the applet at all (clicking their icon does nothing).  Having to restart Cinnamon every hour or so just to get stuff done. There are errors in the log (attached below)

**Steps to reproduce**
1. Just work with a few apps, multiple windows, close some, open others. It won't take long before you notice the problems.

**Other information**
* [.xsession-errors](https://drive.google.com/file/d/1Vfh7a6Nic-rYJ5fb4EM2w3k6YCy2ZnI7/view?usp=sharing)

**Comment by clefebvre** [comment]
(cinnamon:1742): Cjs-WARNING **: 22:14:06.178: JS ERROR: TypeError: this.setStyleOptions is not a function

**Comment by clefebvre** [comment]
Regression introduced by https://github.com/linuxmint/cinnamon/pull/8096. The removed setStyleOptions() function is still being called.

We don't know how to reproduce though, so I'm not sure that's the entire problem.

**Comment by clefebvre** [comment]
@brownsr ^^

**Comment by awunder** [comment]
fwiw, i experience that bug if i choose any of the button label option.. new apps either dont appear at all (sometimes, unable to reproduce) or their icons reimain in the list after the app is already closed (like all the time).
it does NOT happen when showing icons only.

**Comment by awunder** [comment]
just an fyi.. to me this is now fixed
