### ISSUE TITLE
Keyboard bug in Linux mint 22.3 , anyone else experiencing it?

### ISSUE THREAD

**Issue by TutorKidsDad** [linuxmint/Cinnamon#13369]
### Distribution

Linux Mint 22.3

### Package version

Cinnamon 6.6.4

### Graphics hardware in use

Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller

### Frequency

Quite often

### Bug description

I found a weird bug off late Linux mint 22.3 beta, as you can see in the screen recording video the keyboard input (real or on-screen) is not working in anywhere (except in menu search bar) , whether its firefox or libreoffice write BUT only works in the start Menu search box. NOTE that neither real keyboard works NOR the on-screen keyboard.

Two instances when it happens and recreated multiple times 1. after waking from suspend,  2. after restoring from timeshift

### Steps to reproduce

Two instances when it happens and recreated multiple times 1. after waking from suspend,  2. after restoring from timeshift

### Expected behavior

Keyboard should work

### Additional information

Watch it on this youtube video https://youtu.be/DWUJToqsttA , posted by me

**Comment by MenthaSuaveolens** [comment]
After upgrading to LM 22.3 Cinnamon and restarting the computer. i couldn't use the keyboard in LibreOffice, Firefox, gedit, ... Entering my password was working for installing a new update. After installing the latest update (a python-package) and restarting the computer. The problem was solved.

**Comment by knobbysideup** [comment]
Same problem here. Restarting cinnamon fixes it (`<alt><f2>, r`), but only for the current session.  Logging out and back in and the problem is back.

The problem is across 3 different accounts on my laptop and affects both the built in keyboard and the attached USB keyboard.

Guest account that loads a default skel functions normally.

This is on both kernel 6.14 and 6.8, and appears to be a cinnamon problem.

If I open a terminal and try to type, and then restart cinnamon, the keys I had pressed suddenly appear in the terminal.

**Comment by knobbysideup** [comment]
Removing the ibus system package seems to resolve this problem for me.

> Same problem here. Restarting cinnamon fixes it (`<alt><f2>, r`), but only for the current session. Logging out and back in and the problem is back.
> 
> The problem is across 3 different accounts on my laptop and affects both the built in keyboard and the attached USB keyboard.
> 
> Guest account that loads a default skel functions normally.
> 
> This is on both kernel 6.14 and 6.8, and appears to be a cinnamon problem.
> 
> If I open a terminal and try to type, and then restart cinnamon, the keys I had pressed suddenly appear in the terminal.

**Comment by TutorKidsDad** [comment]
Even the crash report is not logging it.Lets hope the issue is solved asap.is it safe to remove (will it not break something?)-- "Removing the ibus system package seems to resolve this problem for me."

**Comment by FCT61** [comment]
Before upgrading to Mint 22.3, I was able to assign Shift + Shift R (or some allowed key combination) to alternate between  keyboard layouts. Now, I manage to  do that only with a mouse,  by clicking on  a keyboard applet on the panel.

**Comment by learning-monk** [comment]
When I updated drivers and restarted the system this issue got resolved.

**Comment by learning-monk** [comment]
An update. Updating drivers didn't resolve the issue.

**Comment by hpoivrot** [comment]
Also since LM 22.3... Doom³ (via dhewm3 1.5.2.1305) acts strangely : with a belgian keyboard, keys "é", "§" and "è" (corresponding to 2, 6 and 7 on an english kb) don't change weapon anymore (they did correctly with 22.2).  It's still 2, 6 and 7 in the configuration window and in the dhewm.cfg file (which, I suppose, dhewm translate from "é", "§" and "è").
Using key to open console (key left to "1" is labelled 2 "squared" and 3 "cubed") does not work either.
Other complain (https://forums.linuxmint.com/viewtopic.php?t=461172) about Steam games being also problematic with 22.3, but my game is the dhewm version, not the Steam version.

**Comment by knobbysideup** [comment]
I just re-installed ibus and the following configuration changes seem to address the problem.

- settings->input method: set input method framework to XIM
- run 'ibus-setup'. Under advanced, check 'Use system keyboard layout'

> Removing the ibus system package seems to resolve this problem for me.
> 
> > Same problem here. Restarting cinnamon fixes it (`<alt><f2>, r`), but only for the current session. Logging out and back in and the problem is back.
> > The problem is across 3 different accounts on my laptop and affects both the built in keyboard and the attached USB keyboard.
> > Guest account that loads a default skel functions normally.
> > This is on both kernel 6.14 and 6.8, and appears to be a cinnamon problem.
> > If I open a terminal and try to type, and then restart cinnamon, the keys I had pressed suddenly appear in the terminal.

**Comment by hpoivrot** [comment]
changing input method did nothing.
removing ibus allowed dhewm3 to use "é/2", "§/6", "è/7" and "2/3" keys again !
but... : https://forums.linuxmint.com/viewtopic.php?p=2732882#p2732882 says that :

_EDIT: do not remove ibus,  #as

    Ibus is required by cinnamon now (even when not using languages with special input modes)._

**Comment by KentCook** [comment]
I have had this issue twice, but my wireless USB keyboard works even though the onboard laptop one doesn't register input. The first time it happened, I was able to load a snapshot and revert the issue. This time even my oldest snapshot did not help.

Edit: my issue may be something else, as reloading Cinnamon doesn't fix it, even temporarily, and I was on 22.2 at the time.

**Comment by drt1951** [comment]
This started 5 days ago on LMDE 7 on a mini-pc with an Intel N95 and wireless keyboard.  This one was upgraded from LMDE 6.

The Alt-F2 usually fixes it but only for a little while.  A wired USB keyboard works fine (at the moment).

All the updates to another mini-pc based on AMD do not cause this problem.  This was a simple LMDE 7 install, not an upgrade.

Before the updates of 5 days ago, a 1080p60 youtube video would drive the CPU temperature to 95C.  After those updates, a 1080p60 video would give a temp as low as 60C.  This makes me wonder if a new graphics driver is causing the keyboard problem.

**Comment by vionandfrederique-afk** [comment]
I am also experiencing the same bug described here on Linux Mint Cinnamon. USB keyboard intermittently stops responding.. Restarting Cinnamon fixes it. Hoping for a thorough fix from the devs. The switching issue is however corrected in the XKB options.

27 Jan. Very erratic keyboard behavior is ongoing after 4 Cinnamon updates.
Changed to a wired keyboard;, but the problem persists.

**Comment by milanovicns** [comment]
Did a bit of research and IBus daemon manual restart corrected the issue with no keyboard input into LibreOffice, Cinnamon built in Calculator, Terminal and likely many other applications. Unsure of what the root cause is, examining the logs and other troubleshooting steps are required.

Had to paste the below command into the terminal to manually restart the IBus daemon:

`ibus-daemon -drx`

Once the above command ran the keyboard typing into the applications started working.

Used Brave browser's AI search to generate IBus answers:

https://search.brave.com/search?q=verify+if+ibus+is+installed+and+running+on+linux&source=web&summary=1&conversation=08af7c1f4a17f7408b1c1e6fad0003493aa9

**Comment by PiperKev** [comment]
Same issue here, Dell Inspiron 3793, LM22.3. Doesn’t matter which kernel I'm on.

**Comment by wolfpackmars2** [comment]
> * settings->input method: set input method framework to XIM
> * run 'ibus-setup'. Under advanced, check 'Use system keyboard layout'
> 
> >

Doing this followed by a reboot seems to have fixed the problem in Chrome. Running LM on a Proxmox VM. Upgraded from 22.2.

I have other systems that I will wait to upgrade - I don't want my Steam to be messed up for example. I already have enough problems keeping my keybindings working in various programs 😛 

Prior to doing the steps above, the only program that seemed to NOT work was chrome. Calc, gedit, xterm at least all seemed to read the keyboard just fine out of the box without any changes.

**Comment by stitheridge** [comment]
> * settings->input method: set input method framework to XIM
> * run 'ibus-setup'. Under advanced, check 'Use system keyboard layout'

These two actions from [knobbysideup](https://github.com/knobbysideup) worked for me. I've had this problem frequently since I upgraded to 22.3 (keyboard input stopped working in xed, LibreOffice etc). I've been restarting Cinnamon each time as a workaround. Hopefully this fix sticks.

**Comment by vionandfrederique-afk** [comment]
@stitheridge 
Where do we find the advanced options?

        settings->input method: set input method framework to XIM
        **run 'ibus-setup'. Under advanced, check 'Use system keyboard layout'**

**Comment by playon69** [comment]
Removing and reinstalling ibus fixed this for me.

**Comment by playon69** [comment]
But after a day, the problem is back!

**Comment by lstubbig** [comment]
Happening for me as well (Mint 22.3, Cinnamon 6.6.7)

**Comment by TutorKidsDad** [comment]
Why is it that there is no action on this open issue till now, I am experiencing frequent mouse and keyboard hangs now a days.Please help.

**Comment by drt1951** [comment]
A couple of weeks ago with XIM, after some updates, the bug came back.  I
switched to ibus and keyboard input has been fine since then.

**Comment by jerrysjerrys** [comment]
I'm not sure if this will contribute to helping solving this issue, but my Linovo G575 Type 4383 I3 CPU Laptop works perfectly without noticeable bugs, where my Toshiba Satellite L775D-S7222 AMD A6-3400M CPU constantly has most all the problems mentioned above, I suspect my Toshiba Satellite is incompatible to this operating system the way it is now, being Toshiba is a less popular brand, after rebooting until recovering keyboard and mouse pad functions, I find that several options are still not able to be turned on/off in the settings, Maybe a different version of Linux might work better, not sure, I'm a bit new to Linux, only a week of experience with a handful of hours, Mint 22.3 Cinnamon,

**Comment by Bytur-dot** [comment]
Got the exact same issue, i'm french and i have an azerty french keyboard, updating to 22.3 from 22.2, and in many games the **é** and other special char didnt work, like in guild wars 2, and in this game, i use **2** / **é** a lot, it was a big issue, but this solution worked :

> settings->input method: set input method framework to XIM
> run 'ibus-setup'. Under advanced, check 'Use system keyboard layout'

For linux noob like me, to run ibus-setup, you need to ALT + F2, then type `ibus-setup`

Thx a lot for the fix

**Comment by lifeisgood456** [comment]
Same issue after upgrading to mint 22.3 from 22.2, azerty keyboard has dead keys in games é/2 and è/7. When I put the layout to qwerty(us) the keys worked again (but of course it's the wrong layout for other keys). I removed ibus a month ago and had no issues since then. Even with ibus being "required" now.

I have been getting this warning every boot since I started using Mint around 20.1. So not sure if it is related I just remembered about it:
`apr 24 22:38:46  slick-greeter-set-keyboard-layout[1403]: Current keyboard configuration: rules:      evdev
apr 24 22:38:46 slick-greeter-set-keyboard-layout[1403]: Applying keyboard configuration: ['setxkbmap', '-model', 'pc105', '-layout', 'be', '-variant', '', '-option', '', '-v']
apr 24 22:38:46  slick-greeter-set-keyboard-layout[1403]: **Result: Warning! Multiple definitions of keyboard model**
apr 24 22:38:46  slick-greeter-set-keyboard-layout[1403]: New keyboard configuration: rules:      evdev
`

**Comment by eomerethaldir-dot** [comment]
Bonjour , 

j'ai un problem similar sur mon **Lenovo Thinkpad E545**
Je suis debutant sur linux et debutant aussi dans le monde de l'informatique

Quand j'ai installe Linux Mind la premier jour tout OK
Mais le jour d'apres apres demarrage impossible d'utiliser le clavier et la souris de l'ordinateur. Meme le clavier digital il bug pour metre mon mot de pass

Apres plusuires restards il finit par remarcher 

Aujourd'hui il a fait la meme chose.

Merci de votre reponse

**Comment by eomerethaldir-dot** [comment]
I found a solution for my problem, i need to go bios and then ESC for normal start and then keyboard works

**Comment by JoannEstonia** [comment]
I had the same problem on a Lenovo Ideapad 520 with 22.3. The keyboard just stopped working while using the machine and it took a reboot to get it back.

**Comment by alexbottoni** [comment]
Same problem here with a new Acer Aspire Go 15, AMD processor, with Linux Mint 22.3 and Italian language pack + keyboard layout. No solution found so far. The problem always shows up after a timed sleep. Linux Mint switches to US keyboard. Caps Lock is enabled and cannot be switched off, keeping me from logging in and forcing me to restart the system.

**Comment by TutorKidsDad** [comment]
Don't know how to create the error log for this as there is non
generated.moreover it's quite an old bug now with many users
encountering the same problem ,hope for speedy correction.
