### ISSUE TITLE
4.8.3 fails to build on arm64 in Ubuntu 21.04 with "cinnamon-global-private.h:23:10: fatal error: cinnamon-enum-types.h: No such file or directory"

### ISSUE THREAD

**Issue by rikmills** [linuxmint/cinnamon#9785]
```
 * Version: 4.8.3
 * Ubuntu 21.04
 * arm64
 ```

**Issue**

4.8.3 fails to build on arm64 in Ubuntu 21.04 with 

```
In file included from ../src/run-js-test.c:40:
../src/cinnamon-global-private.h:23:10: fatal error: cinnamon-enum-types.h: No such file or directory
   23 | #include "cinnamon-enum-types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

https://launchpad.net/ubuntu/+source/cinnamon/4.8.3-3

https://launchpad.net/ubuntu/+source/cinnamon/4.8.3-3/+build/20712903

Note: applying ea573265 to a PPA test build fails to fix the issue, as does disabling build parallelisation.

Failing build for arm64 with ea57326 applied: https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3997/+sourcepub/11942714/+listing-archive-extra

Failing build for amd64 in Mint daily: https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds/+sourcepub/11827412/+listing-archive-extra (includes ea57326)

**Steps to reproduce**

Build in Ubuntu archive

**Expected behaviour**

Builds on arm64

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02

**Comment by rikmills** [comment]
> This should have fixed it [ea57326](https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02)

As already said, it does not.

**Comment by leigh123linux** [comment]
> > This should have fixed it [ea57326](https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02)
> 
> As already said, it does not.

They haven't applied that patch to https://launchpad.net/ubuntu/+source/cinnamon/4.8.3-3

**Comment by rikmills** [comment]
> > > This should have fixed it [ea57326](https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02)
> > 
> > 
> > As already said, it does not.
> 
> They haven't applied that patch to https://launchpad.net/ubuntu/+source/cinnamon/4.8.3-3

I already said:

> **Note: applying ea57326 to a PPA test build fails to fix the issue**

**Comment by rikmills** [comment]
@leigh123linux New test build with ea57326 applied

https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3997/+sourcepub/11942714/+listing-archive-extra

**Comment by ItzSwirlz** [comment]
**build still fails**

I'm going to build this on my Pi and see what happens. In Debian Cinnamon due to it's dependency chain was bumped from experimental to unstable (see testing migration excuses at https://tracker.debian.org/cinnamon for more details).

I didn't build since commit ea57326. But normally it did build fine for me on arm64 on my Pi. I'm dealing with the dependency chain right now on my Pi so when it's done I'll let you know.

**Comment by rikmills** [comment]
I also notice that the daily amd64 build here also fails in the exact same way, **and** includes ea57326

https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds/+sourcepub/11827412/+listing-archive-extra

**Comment by ItzSwirlz** [comment]
welp looks like building for my Pi is out with cinnamon repo cuz cjs stuff... (don't worry about it.) I suggest building without ea57326 and seeing what happens.

**Comment by vladimir-didenko** [comment]
Yes, the parallel build is still broken. With ea57326 applied builder machine fails to build cinnamon on some architectures e.g.
```
[x86_64] cc -Isrc/cinnamon.p -Isrc -I../src -I. -I.. -Isrc/st -I../src/st -I../src/st/croco -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cjs-1.0 -I/usr/include/gobject-introspection-1.0 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/muffin/clutter-0 -I/usr/include/pango-1.0 -I/usr/include/json-glib-1.0 -I/usr/include/muffin/cogl -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cinnamon-menus-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/gtk-3.0 -I/usr/include/muffin -I/usr/include/cinnamon-desktop -I/usr/include/polkit-1 -I/usr/include/startup-notification-1.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gstreamer-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch '-DDATADIR="/usr/share"' '-DLIBDIR="/usr/lib64"' '-DBINDIR="/usr/bin"' '-DCINNAMON_DATADIR="/usr/share/cinnamon"' '-DJSDIR="/usr/share/cinnamon/js"' '-DMUFFIN_TYPELIB_DIR="/usr/lib64/muffin"' -Wno-deprecated-declarations -Wno-deprecated -Wno-declaration-after-statement -frecord-gcc-switches -Wall -g -O2 -pthread -DMUFFIN_MAJOR_VERSION=4 -DMUFFIN_MINOR_VERSION=8 -DMUFFIN_MICRO_VERSION=0 -DMUFFIN_PLUGIN_API_VERSION=0 '-DLOCALEDIR="/usr/share/locale"' '-DCINNAMON_PKGLIBDIR="/usr/lib64/cinnamon"' -MD -MQ src/cinnamon.p/main.c.o -MF src/cinnamon.p/main.c.o.d -o src/cinnamon.p/main.c.o -c ../src/main.c
[x86_64] --
[x86_64]                  from ../src/main.c:25:
[x86_64] ../src/st/st-box-layout-child.h:24:10: fatal error: st-enum-types.h: No such file or directory
[x86_64]    24 | #include "st-enum-types.h
```

**Comment by rikmills** [comment]
> welp looks like building for my Pi is out with cinnamon repo cuz cjs stuff... (don't worry about it.) I suggest building without [ea57326](https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02) and seeing what happens.

The original Ubuntu archive build (1st link in the issue) is one without that commit, as it postdates the 4.8.3 tar release

**Comment by ItzSwirlz** [comment]
Looking back at the commit history, ea57326 is part of several commits that should be reverted.

The following commits would have to be reverted aswell:
https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02
https://github.com/linuxmint/cinnamon/pull/9725/commits/8793592fdb9e3d02210880776e9109f74a84a4cd
https://github.com/Cobinja/cinnamon/commit/33e26383d7470fb9e81605db00173088e4d95ab1

**Comment by leigh123linux** [comment]
4.8.1 failed here for s390x

https://kojipkgs.fedoraproject.org//work/tasks/550/57040550/build.log

And https://github.com/linuxmint/cinnamon/commit/ea5732651ab62ca4153eaea9c6d5364f26187e02 fixed it for 4.8.3

https://koji.fedoraproject.org/koji/buildinfo?buildID=1658053

**Comment by rikmills** [comment]
Sadly, ea57326 completely fails to fix the 4.8.3 arm64 build in Ubuntu.

**Comment by mtwebster** [comment]
It's failing on our ppa also.

**Comment by mtwebster** [comment]
Hi can you try the latest cinnamon?

https://github.com/linuxmint/cinnamon/commit/480568c33385d1705e72c55cabbd89e2c73b5169

I can't reproduce it personally, but reading a bit more in the meson manual this may fix it :)

**Comment by vladimir-didenko** [comment]
@mtwebster It resolved the issue for me. Tested on aarch64, armh, i586, ppc64le, x86_64 platforms. Thank you!

**Comment by leigh123linux** [comment]
@mtwebster  All six arches build here https://koji.fedoraproject.org/koji/taskinfo?taskID=58050024

**Comment by mtwebster** [comment]
This fixed the PPA build as well, I'm going to assume this is resolved.

Thanks all!

**Comment by rikmills** [comment]
> Hi can you try the latest cinnamon?
> 
> [480568c](https://github.com/linuxmint/cinnamon/commit/480568c33385d1705e72c55cabbd89e2c73b5169)

Testing now......

**Comment by rikmills** [comment]
Looks like that did it!

https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3997/+sourcepub/11943234/+listing-archive-extra

Thanks to all those that helped.....
